### ISSUE TITLE
Inconsistency between endpoints 

### ISSUE THREAD

**Issue by robcxyz** [icon-project/goloop#110]
When querying sejong API, I am not able to query contract method on my own nodes vs solidwallet nodes. 

```python
import requests
import json

url = "http://108.61.103.8:9010/api/v3"
payload = {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "icx_call",
    "params": {
        "to": "cx79a1d066c9bab28090d9fc621a8212ca681a3553",
        "dataType": "call",
        "data": {"method": "name"},
    },
}

r = requests.post(url=url, data=json.dumps(payload)).json()
assert r['error']['message'] == 'SystemError(-30001): E0001:ProxyIsClosed'

url = "https://sejong.net.solidwallet.io/api/v3"
r = requests.post(url=url, data=json.dumps(payload)).json()
assert r['result'] == 'Snapshot'
```

Reported this before #99 but wanted to give a concrete example.  Nothing is showing in the logs on the node side. It is able to respond to other requests such as `icx_getScoreApi` on this contract and others but failing on this call for this contract and about 25% of all the other contracts on Sejong.

**Comment by sink772** [comment]
@robcxyz The problem seems to be related to your node configuration, as the issue only occurred on your node.  Can you restart your node with `GOLOOP_LOG_LEVEL=trace` to get more verbose logs? And let us know the logs when the problem occurred.

**Comment by robcxyz** [comment]
@sink772 

Set logging to trace and looked through logs and not seeing any relevant information. Perhaps you can tell me what I should be looking for as from what I can tell this isn't showing in the logs. Does RPC traffic get logged internally?

Also this isn't just one node, this is 8 nodes all displaying the same behavior.  And as far as the config, not much going on. Was advised by jinwoo to map ports but that shouldn't have anything to do with this issue. 

```
    environment:
      SERVICE: SejongNet
      GOLOOP_LOG_LEVEL: "trace"
      FASTEST_START: "true"
      ROLE: 0
      IS_AUTOGEN_CERT: "true"
      GOLOOP_P2P_LISTEN: ":7110"
      GOLOOP_RPC_ADDR: ":9010"
```
