### ISSUE TITLE
Node is stuck in `candidate` status while in main after migration 

### ISSUE THREAD

**Issue by robcxyz** [icon-project/goloop#111]
Recently I migrated my node on mainnet which was synced up as a citizen and then converted to a prep and it is now stuck as being a candidate and accruing penalties.  Node was migrated over 1 term ago and should have come back into rotation. 

To migrate the node I ran:
```
preptools setPRep --config preptools_config.json --node-address hx7f035c0fc573cb6c1ff17cd2b6678f0a17f491f3 --prep-json registerPRep.json
```
Which resulted in this Tx hash: [https://tracker.icon.community/transaction/0x6dc6980b8aee3d9817b2b2eaed743ba149f8b92cd30a21df37ef1ca5570c1a5c](https://tracker.icon.community/transaction/0x6dc6980b8aee3d9817b2b2eaed743ba149f8b92cd30a21df37ef1ca5570c1a5c)

And then verifying via `getPrep` RPC that the data is in fact on chain, scraping the `/metrics` endpoint and validating a few metrics indicative of a healthy node. 

```python 
import requests
import json

url = "https://api.icon.community/api/v3"
payload = {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "icx_call",
    "params": {
        "to": "cx0000000000000000000000000000000000000000",
        "dataType": "call",
        "data": {
            "method": "getPRep",
            "params": {
                "address": "hxfc56203484921c3b7a4dee9579d8614d8c8daaf5"
            }
        }
    },
}

r = requests.post(url=url, data=json.dumps(payload)).json()

assert r['result']['grade'] == '0x2'  # This shows the node is in "candidate" state  

p2p_endpoint = r['result']['p2pEndpoint']
assert p2p_endpoint == '139.180.184.203:7100'
metrics_endpoint = 'http://' + p2p_endpoint.split(':')[0] + ':9000/metrics'
assert metrics_endpoint == 'http://139.180.184.203:9000/metrics'

r = requests.get(url=metrics_endpoint)
for i in r.text.split('\n'):
    if i.startswith('goloop_consensus_height_duration'):
        goloop_consensus_height_duration = int(i.split()[-1])
        # These are good ranges for this metric showing healthy node
        assert goloop_consensus_height_duration > 1500
        assert goloop_consensus_height_duration < 2500
    elif i.startswith('goloop_consensus_height'):
        goloop_consensus_height = int(float(i.split()[-1]))
        # Show that it is at a recent block (it is synced...)
        assert goloop_consensus_height > 50460693

```

Nothing in the logs is telling me that anything is wrong. Node has been restarted several times to make sure new config was brought in.

```
  mainnet:                                                                                                                                                                                                         
    image: 'iconloop/icon2-node'                                                                                                                                                                                   
    restart: "on-failure"                                                                                                                                                                                          
    stdin_open: true                                                                                                                                                                                               
    cap_add:                                                                                                                                                                                                       
      - SYS_TIME                                                                                                                                                                                                   
    volumes:                                                                                                                                                                                                       
      - ./mainnet/data:/goloop/data                                                                                                                                                                                
      - ./mainnet/logs:/goloop/logs                                                                                                                                                                                
      - ./mainnet/config:/goloop/config                                                                                                                                                                            
    environment:                                                                                                                                                                                                   
      SERVICE: MainNet                                                                                                                                                                                             
      GOLOOP_LOG_LEVEL: "debug"                                                                                                                                                                                    
      FASTEST_START: "true"                                                                                                                                                                                        
      ROLE: 3                                                                                                                                                                                                      
      IS_AUTOGEN_CERT: "true"                                                                                                                                                                                      
      GOLOOP_P2P_LISTEN: ":7100"
      GOLOOP_RPC_ADDR: ":9000"
      KEY_PASSWORD: "nunyabiznis"
      KEY_STORE_FILENAME: keystore
    ports:
      - 7100:7100
      - 9000:9000
```

Which successfully loads the keystore and is the right address:

```
Successfully loaded Keystore file(json), address=hx40f9e6a0b54b8dd9d90732aaee4f9789550092c7, file=/goloop/config/keystore
```

Last tidbit that might be useful is that it didn't seem like this node was peered properly with the network but I am still looking into that.
